server:
  port: 8088
  address: 0.0.0.0

spring:
  application:
    name: syai-image-generator
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

image-generator:
  output-dir: generated
  python-executable: C:/Users/vidha/AppData/Local/Programs/Python/Python311/python.exe
  python-script: C:/Users/vidha/AndroidStudioProjects/SyAi-Public/image-generator/python/stable_diffusion_runner.py
  model-id: Lykon/DreamShaper
  device: cuda
  allow-origins:
    - "*"

#segmind/tiny-sd -- cpu
#runwayml/stable-diffusion-v1-5 --alternate model to try for gpu based loading